### PR TITLE
Rename branch and add file

### PR DESCRIPTION
**Pull request by spraints**
@pmiossec - re https://github.com/git-tfs/git-tfs/pull/692#issuecomment-68182885

> Maybe use an extension method to add an overload of the Fetch methods, so there's less churn all over.

The first 2 commits do this.

> I would pull the two rename-related state fields out into an object or a struct, and call it something like RenameState or RenameContext or FetchContext. This is just a different way to do the thing you did with the interface. This could let you create a single context object in the caller (InitBranch, if I read it right), and not worry about extracting information from the FetchResult.

The last commit does this.

If you like them, feel free to cherry-pick onto your branch.

### CODE REVIEW

**Comment by spraints** [comment]
The existing tests pass, so it'd be great to have a test that covers the breaking scenario here, too. I can add one. Can you describe some the TFS changesets that would demonstrate the problem?

**Comment by pmiossec** [comment]
>The existing tests pass, so it'd be great to have a test that covers the breaking scenario here, too. I can add one.

For the moment, there is no tests about renaming support :( So you're right that this PR is the best time to add one!

But adding a test for the rename scenario will be a hard job...And I think that the regression introduced is a very special case that I have in my tfs test repository because I have made multiple renames successively (and write a test case for this case will be even harder) .

For the moment, I didn't find time to investigate or think about how to write a test :(
My tfs test repository that help me develop the feature (and debug my code and find the regression):

    git tfs clone https://tfs.codeplex.com:443/tfs/TFS16 $/vtccds/trunk . --with-branches --username=vtccds_cp@snd --password=vtccds

And the result should be that :

     https://github.com/pmiossec/vtccds

The branch where the regression occurs is `renamed3`.
The main idea behind this PR is that a rename changeset is that a changeset straddles 2 branches (if you query tfs for the 2 paths, it returns the changeset in both changeset history). This changeset could be seen as the last changeset of the first branch (what is done --wrong-- in the current code) or as the first changeset of the second branch (what the current PR do).
The second is the best one because if there is other changes, git-tfs could then take them into account and process them!
One of the consequence is that the git-tfs metadata change from `git-tfs-id: [https://tfs.codeplex.com:443/tfs/TFS16]$/vtccds/testRename;C25200` (old bad metadata) to
`git-tfs-id: [https://tfs.codeplex.com:443/tfs/TFS16]$/vtccds/afterRename;C25200` (new good metadata).

For the test repository, for the branch `renamed3`, we should have these metadata (`*` is for renamed changeset, following by the name of the new branch) :

    33407* $/vtccds/renamed3
    27509  $/vtccds/renamedTwice
    27508* $/vtccds/renamedTwice
    25202  $/vtccds/afterRename
    25200* $/vtccds/afterRename
    25199  $/vtccds/testRename
    25198  $/vtccds/testRename

The changeset `33407` must contain also other changes than just the rename of the branch (file `file2` added and file `file` modified).

You could see all that in the reference repository `https://github.com/pmiossec/vtccds`

So, I think that our test should return in the history a rename changeset (I don't know how at the moment) and we should assert that the metadata of the commit created contains the tfs path of the renamed branch.

And perhaps that for the regression, we will have to write a test with 1 rename changeset, then 1 normal changeset and finally a rename changeset again.

And I could imagine 2 successive renames, but I don't even know if the code I wrote could support this case well....

**Comment by spraints** [comment]
I'll try to get a test case written this week.

**Comment by pmiossec** [comment]
I have worked on that some times ago but, even if I have done some
interesting things, I have failed at some point :-( I will try to push that
if you want to have a look (when I will be in front of my computer) because
I don't find time to work on that (and won't be able in the near
future....)

**Comment by pmiossec** [comment]
Very bad news!
I have lost all the work I have done. :( I think I have mad a `git reset` of all my work some days ago, thinking I have commited it... Thus, now way to recover it.......
Such a beginner error, I am very disappointed !!! It never happened since I worked with git and it need to happened when working on this hard stuff :(

I will try to see if I could rewrite part of it quickly....

**Comment by pmiossec** [comment]
very little first step of what I did : https://github.com/pmiossec/git-tfs/commit/b03cfee285d8fb6d261d0751f6c8d29ac94c75a7

Need debugging and continuing in this way...but commit message explain the idea behind what should be done...

**Comment by spraints** [comment]
I didn't see your comments till just now. I got started on some test data in 8ebeadd. The files in that commit were generated by a [ruby script that converts the vtccds TFS repo into integration test data](https://github.com/git-tfs/git-tfs-test-builder). There are probably some bits related to branch metadata that are missing, but I assume we can add those relatively easily.

**Comment by pmiossec** [comment]
Really good idea!!!! :sparkles: 
I have worked on that generated test. Feel free to read the commit comment ( I have created a branch https://github.com/git-tfs/git-tfs/tree/rename_branch_and_add_file_With_test on this repository to be able to work together more easily).

For the moment, a repository is generated during the test but :

* the `Read()` should be fixed to return the good content (I didn't know how it was written by the ruby script)
* the renamed branch failed and are not cloned. It's a shame because that's the aim of this test :(

I don't know if I will be able to work again on that soon.....

**Comment by spraints** [comment]
> I have created a branch https://github.com/git-tfs/git-tfs/commits/rename_branch_and_add_file_With_test on this repository to be able to work together more easily

:metal: good idea. I pushed a couple of fixes to that branch.

> the Read() should be fixed to return the good content (I didn't know how it was written by the ruby script)

TFS was gzip'ing the data. `Read` now decompresses it (b948e30c104696b73fa69bd7d0a064efb8744ea5). The test created a repository, so 62daac6cf2c9e8403b354775f90dd6cc16ee8301 captures the commits that were generated.

> the renamed branch failed and are not cloned. It's a shame because that's the aim of this test :(

I think that's why we were adding the tests here? I added the test fixtures to my broken branch (this PR), so now I think we update assertions in `WhenCloningVtccds` so that they include the expected renamed branch?

**Comment by pmiossec** [comment]
I have adapted the test and TfsHelper.VsFake to obtain the real commit sha (exactly the one obtained when using git-tfs to clone the repository: https://github.com/pmiossec/vtccds).

There is now some assert to make them pass.....

**Comment by spraints** [comment]
To make it easier to see the diff & commits, I opened https://github.com/git-tfs/git-tfs/pull/718.

**Pull request closed without merging**
